config/routes.rb
Rails.application.routes.draw do
  require "sidekiq/web"

  namespace :admin do
    mount Sidekiq::Web => "/sidekiq"
    resources :users

    root to: "users#index"
  end

  resources :photos

  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]

  get "/sign_up" => "users#new"
  get "/sign_in" => "sessions#new"
  get "/sign_out" => "sessions#destroy"

  # root "/pages/home.html"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/guest_user.rb
class GuestUser < User
  def admin?
    false
  end

  def email
  end

  def name
    "Guest User".freeze
  end

  def logged_in?
    false
  end
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user
  has_one_attached :image_file

  validates :file_name, presence: true
  validates :geoprivacy, presence: true
  validates :slug, presence: true, uniqueness: { scope: :user_id }
end

app/models/user.rb
class User < ApplicationRecord
  # has_secure_password

  validates :email, presence: true, uniqueness: true
  validates :password_digest, presence: true

  def logged_in?
    true
  end
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_actions.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    before_action :authenticate_admin

    def authenticate_admin
      # TODO Add authentication logic here.
    end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = User.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   User.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Oath::ControllerHelpers
  protect_from_forgery with: :exception

  def current_user
    super || GuestUser.new
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :require_login #, only: [:new, :create, :edit, :update, :delete]

  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.new(photo_params)

    respond_to do |format|
      if @feed.save
        format.html do
          flash[:success] = I18n.t(".success")
          redirect_to @feed
        end

        format.js do
          flash.now[:success] = I18n.t(".success")
        end
      else
        format.html do
          flash.now[:error] = I18n.t(".failure")
          render :new
        end

        format.js do
          flash.now[:error] = I18n.t(".failure")
          render :new
        end
      end
    end
  end

  private

  def photo_params
    params.require(:photo).permit(
      :slug,
      :title,
      :description,
      :copyright_year,
      :geoprivacy,
      :latitude,
      :longitude,
      :shutter_speed,
      :aperture
    ).merge(user: current_user)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create], raise: false

  def new; end

  def create
    user = authenticate_session(session_params)

    if sign_in(user)
      flash[:notice] = I18n.t("sessions.create.success")

      redirect_to root_path
    else
      flash[:notice] = I18n.t("sessions.create.failure")

      render :new
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create], raise: false

  def new
    @user = User.new
  end

  def create
    @user = sign_up(user_params)

    if @user.valid?
      sign_in(@user)
      flash[:notice] = t(".success")

      redirect_to root_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  def user_facing_flashes
    flash.to_hash.slice("alert", "error", "notice", "success")
  end
end

app/views/application/_analytics.html.erb
<% if ENV["SEGMENT_KEY"] %>
  <script type="text/javascript">
    window.analytics=window.analytics||[],window.analytics.methods=["identify","group","track","page","pageview","alias","ready","on","once","off","trackLink","trackForm","trackClick","trackSubmit"],window.analytics.factory=function(t){return function(){var a=Array.prototype.slice.call(arguments);return a.unshift(t),window.analytics.push(a),window.analytics}};for(var i=0;i<window.analytics.methods.length;i++){var key=window.analytics.methods[i];window.analytics[key]=window.analytics.factory(key)}window.analytics.load=function(t){if(!document.getElementById("analytics-js")){var a=document.createElement("script");a.type="text/javascript",a.id="analytics-js",a.async=!0,a.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n)}},window.analytics.SNIPPET_VERSION="2.0.9",
    window.analytics.load("<%= ENV["SEGMENT_KEY"] %>");
    window.analytics.page();
  </script>
<% end %>

app/views/application/_css_overrides.html.erb
<% if Rails.env.test? %>
  <style type="text/css">
    * {
      transition-property: none !important;
    }
  </style>
<% end %>

app/views/application/_flashes.html.erb
<% if flash.any? %>
  <div class="flashes" data-role='flash-notice'>
    <% user_facing_flashes.each do |key, value| -%>
      <div class="flash-<%= key %>"><%= value %></div>
    <% end -%>
  </div>
<% end %>

app/views/application/_footer.html.erb
<section id="footer">
  <ul>
    <li><%= I18n.t('footer.copyright_html') %></li>
    <li><%= link_to 'Terms of Use', page_path('terms-of-use') %></li>
    <li><%= link_to 'Privacy Policy', page_path('privacy-policy') %></li>
    <li>Colophon</li>
    <li>Feeds</li>
  </ul>
</section>

app/views/application/_header.html.erb
<section id="header">
  <h1><%= link_to I18n.t('header.title'), root_path %></h1>
  <p><%= I18n.t('header.byline') %></p>

  <%= render "user_actions" -%>
</section>

app/views/application/_javascript.html.erb
<%= javascript_include_tag :application %>

<%= yield :javascript %>

<%= render "analytics" %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.fx.off = true;
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

app/views/application/_user_actions.html.erb
  <section data-role="user-actions">
    <% if !current_page?(sign_up_path) && !current_page?(sign_in_path) %>
      <% if current_user.logged_in? %>
        <ul>
          <li><%= I18n.t("account_actions.hello") %></li>
          <li><%= link_to I18n.t("account_actions.sign_out"), sign_out_path %></li>
        <ul>
      <% else %>
        <ul>
          <li><%= link_to I18n.t("account_actions.sign_in"), sign_in_path %></li>
          <li><%= link_to I18n.t("account_actions.sign_up"), sign_up_path %></li>
        </ul>
      <% end %>
    <% end %>
  </section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="ROBOTS" content="NOODP" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <%#
    Configure default and controller-, and view-specific titles in
    config/locales/en.yml. For more see:
    https://github.com/calebthompson/title#usage
  %>
  <title><%= title %></title>
  <link href="https://unpkg.com/m-@1.2.4/dist/min.css" rel="stylesheet">
  <%= stylesheet_link_tag :application, media: "all" %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= body_class %>">
  <%= render "header" -%>
  <%= render "flashes" -%>

  <%= yield %>
  <%= render "footer" %>
  <script src="https://unpkg.com/m-@1.2.4/dist/min.js" defer></script>
  <%= render "javascript" %>
  <%= render "css_overrides" %>
</body>
</html>

app/views/pages/home.html.erb
<h1>Photo sales: Hello, world</h1>

<p>Hello from walls.corpus Photo sales</p>

app/views/pages/privacy-policy.html.erb
<h1>Privacy Policy</h1>

<p>Forthcoming</p>

app/views/pages/terms-of-use.html.erb
<h1>Terms of Use</h1>

<p>Forthcoming</p>

app/views/photos/_form.html.erb
<%= simple_form_for @photo do |form| %>
  <%= form.input :slug %>
  <%= form.input :title %>
  <%= form.input :description %>
  <%= form.input :copyright_year %>
  <%= form.input :geoprivacy, as: :radio_buttons %>
  <%= form.input :latitude %>
  <%= form.input :longitude %>
  <%= form.input :shutter_speed %>
  <%= form.input :aperture %>

  <!-- File input -->

  <%= form.button :submit %>
<% end %>

app/views/photos/new.html.erb
<h1><%= I18n.t("photos.new.title") %></h1>

<%= render partial: 'form', photo: @photo %>

<p>Below the form</p>

app/views/refills/_flashes.html.erb
<div class="flash-success">
  <span>This is a success message <a href="#">with a link</a></span>
</div>

<div class="flash-error">
  <span>This is an error message <a href="#">with a link</a></span>
</div>

<div class="flash-notice">
  <span>This is an notice message <a href="#">with a link</a></span>
</div>

<div class="flash-alert">
  <span>This is an alert message <a href="#">with a link</a></span>
</div>

app/views/users/new.html.erb
<%= simple_form_for @user do |form| %>
  <% if @user.errors.any? %>
    <%= pluralize(@user.errors.count, "error") %> prevented your account from being created:
    <ul>
      <% @user.errors.full_messages.each do |error_message| %>
        <li><%= error_message %></li>
      <% end %>
    </ul>
  <% end %>

  <%= form.input :name %>
  <%= form.input :email, require: true %>
  <%= form.input :password, require: true %>
  <%= form.button :submit %>
<% end %>